# Put this file to %APPDATA%\xwslgit\config.yaml to configure behaviors of xwslgit
debug:
  # set true to log xwslgit activities.
  # useful for the case xwslgit doesn't work expected and diagnose the behavior.
  enabled: false
  # path to output logs. %APPDATA%\xwslgit\debug.log is used if not configured.
  logfile: C:\Windows\Temp\xwslgit.log
  # envs are environment variables to log.
  envs:
    - GIT_DIR
    - GIT_WORKING_TREE
    - GIT_SSH
detection:
  # detect target WSL distribution from arguments to `git` command.
  # if not set to true, detects only from the working directory.
  useArguments: true
windowsGit:
  # You can configure path to Git for Windows explicitly
  # though xwslgit automatically find that.
  path: C:\Program Files\Git\cmd\git.exe
distributions:
  Ubuntu-22.04:
    # You can override the command to launch git on WSL
    # arguments to git will be appended to the last.
    command:
      - wsl
      - -d
      - Ubuntu-22.04
      - --shell-type
      - none
      - --
      - git
    # true for escaping arguments.
    # useful especially when without `--shell-type none`
    escapeArguments: false
